# shellcheck shell=bash
# shellcheck disable=SC2154,SC2034  # Variables from core/config, used in other files
# ============================================================================
# Input: Parse Claude JSON and calculate token metrics
# Provides: model, cwd, sid, transcript, ctx_size, input_tok,
#           cache_read, cache_create, cost,
#           total_used (input+cache_read+cache_create), effective_max, true_pct,
#           msg_fmt, buffer_fmt, total_fmt, eff_fmt, has_usage_data
# ============================================================================

eval "$(echo "$input" | jq -r '
  @sh "model=\(.model.display_name // "unknown")
  cwd=\(.workspace.current_dir // ".")
  sid=\(.session_id // "")
  transcript=\(.transcript_path // "")
  ctx_size=\(.context_window.context_window_size // 200000)
  input_tok=\(.context_window.current_usage.input_tokens // 0)
  cache_read=\(.context_window.current_usage.cache_read_input_tokens // 0)
  cache_create=\(.context_window.current_usage.cache_creation_input_tokens // 0)
  cost=\(.cost.total_cost_usd // 0)"
')"

# Total context = input + cache (what fills the context window)
# Output tokens are generated BY Claude, not consumed from context
total_used=$((input_tok + cache_read + cache_create))

# Effective max = full context size
effective_max=$ctx_size

# Only show usage if API provides data
if [ "$total_used" -gt 0 ]; then
    true_pct=$((total_used * 100 / effective_max))
    [ "$true_pct" -gt 100 ] && true_pct=100
    has_usage_data=1
else
    true_pct=0
    has_usage_data=0
fi

msg_fmt=$(fmt_k "$total_used")
buffer_fmt=$(fmt_k "$CTX_BUFFER")
total_fmt=$(fmt_k "$total_used")
eff_fmt=$(fmt_k "$effective_max")
